spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway
    username: flyway
    password: flyway
  flyway:
    enabled: true
    validate-migration-naming: true
    baseline-on-migrate: true
